src/main/java/de/saller/shoppingcart/model/Product.java
package de.saller.shoppingcart.model;

import java.util.Objects;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

@NamedQueries({
    @NamedQuery(name = Product.findAll, query = "SELECT p FROM Product p")
})

@Entity
public class Product {

    public static final String findAll = "Product.findAll";
    
    @GeneratedValue
    @Id
    private Long id;
    private String name;
    private double price;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Product other = (Product) obj;
        
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        
        if (Double.doubleToLongBits(this.price) != Double.doubleToLongBits(other.price)) {
            return false;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        return true;
    }
    
    

}

src/main/java/de/saller/shoppingcart/model/ShoppingCart.java
package de.saller.shoppingcart.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Transient;

@NamedQueries({
    @NamedQuery(name = ShoppingCart.findAll, query = "SELECT c FROM ShoppingCart c")
})

@Entity
public class ShoppingCart {

    public static final String findAll = "ShoppingCart.findAll";

    @GeneratedValue
    @Id
    private Long id;
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.MERGE)
    private List<ShoppingCartItem> items;
    @Transient
    private double total;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public List<ShoppingCartItem> getItems() {
        return items;
    }

    public void setItems(List<ShoppingCartItem> items) {
        this.items = items;
    }

    public double getTotal() {
        return total;
    }

    public void setTotal(double total) {
        this.total = total;
    }

    public int getNumberOfItems() {
        return items.size();
    }

    public void addShoppingCartItem(ShoppingCartItem item) {
        this.items.add(item);
    }

}

src/main/java/de/saller/shoppingcart/model/ShoppingCartItem.java
package de.saller.shoppingcart.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class ShoppingCartItem {

    @GeneratedValue
    @Id
    private Long id;
    @ManyToOne
    private Product product;
    @ManyToOne
    private ShoppingCart shoppingCart;
    private int quantity;

    public ShoppingCartItem() {
    }
    
    public ShoppingCartItem(ShoppingCart shoppingCart, Product product) {
        this.shoppingCart = shoppingCart;
        this.product = product;
        this.quantity = 1;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ShoppingCart getShoppingCart() {
        return shoppingCart;
    }

    public void setShoppingCart(ShoppingCart shoppingCart) {
        this.shoppingCart = shoppingCart;
    }
            
    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    
    public void increaseQuantityByONE() {
        this.quantity++;
    }
    
    public double getTotal() {
        return product.getPrice() * this.quantity;
    }

}

src/main/java/de/saller/shoppingcart/controller/EditShoppingCartController.java
package de.saller.shoppingcart.controller;

import de.saller.shoppingcart.data.ShoppingCartItemSupplier;
import de.saller.shoppingcart.model.Product;
import de.saller.shoppingcart.model.ShoppingCartItem;
import java.io.Serializable;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

@ViewScoped
@Named
public class EditShoppingCartController implements Serializable {

    @Inject
    private ShoppingCartItemSupplier shoppingCartItemsSupplier;

    private Product selectedProduct;

    public void doRemoveShoppingCartItem(ShoppingCartItem item) {
        shoppingCartItemsSupplier.removeShoppingCartItem(item);
    }

    public String doOK() {
        return PageNavigation.LIST_SHOPPINGCARTS;
    }

    public void updateItemQuantity(ShoppingCartItem item) {
        shoppingCartItemsSupplier.updateShoppingCartItem(item);
    }

    public void addItemToCart() {
        shoppingCartItemsSupplier.addShoppingCartItem(selectedProduct);
    }

    public Product getSelectedProduct() {
        return selectedProduct;
    }

    public void setSelectedProduct(Product selectedProduct) {
        this.selectedProduct = selectedProduct;
    }
    
    
}

src/main/java/de/saller/shoppingcart/controller/ListShoppingCartsController.java
package de.saller.shoppingcart.controller;

import de.saller.shoppingcart.data.ShoppingCartItemSupplier;
import de.saller.shoppingcart.model.ShoppingCart;
import java.io.Serializable;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

@ViewScoped
@Named
public class ListShoppingCartsController implements Serializable {
    
    @Inject
    private ShoppingCartItemSupplier shoppingCartItemsSupplier;
    
    public String doEditShoppingCart(ShoppingCart cart) {    
        shoppingCartItemsSupplier.setCurrentShoppingCart(cart);
        return PageNavigation.EDIT_SHOPPINGCART;
    }
    
}

src/main/webapp/editShoppingCart.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>
        <ui:composition template="./template.xhtml">
            <ui:define name="content">

                <h1>Shopping Cart #{currentShoppingCart.id}</h1>

                <p:messages autoUpdate="true" showDetail="true"/>

                <h:form>

                    <p:dataTable id="itemTable" value="#{currentShoppingCart.items}" var="item">

                        <p:column>
                            <f:facet name="header">Productname</f:facet>
                            <h:outputText value="#{item.product.name}"/>
                        </p:column>

                        <p:column style="text-align: center">
                            <f:facet name="header">Quantity</f:facet>

                            <p:commandLink value="Remove" 
                                           update="itemTable"
                                           actionListener="#{editShoppingCartController.doRemoveShoppingCartItem(item)}"/>
                            <p:spacer width="20px"/>
                            <p:spinner value="#{item.quantity}" size="2" min="1">
                                <p:ajax process="@this" update="itemTable"
                                        listener="#{editShoppingCartController.updateItemQuantity(item)}"/>
                            </p:spinner>

                        </p:column>

                        <p:column style="text-align: right">
                            <f:facet name="header">Price</f:facet>
                            <h:outputText value="#{item.product.price}">
                                <f:convertNumber type="currency" locale="de_DE"/>
                            </h:outputText>
                            <f:facet name="footer">
                                <h:outputText value="Total:"/>
                            </f:facet>
                        </p:column>

                        <p:column style="text-align: right">
                            <f:facet name="header">Total</f:facet>
                            <h:outputText value="#{item.total}">
                                <f:convertNumber type="currency" locale="de_DE"/>
                            </h:outputText>    
                            <f:facet name="footer">
                                <h:outputText value="#{currentShoppingCart.total}">
                                    <f:convertNumber type="currency" locale="de_DE"/>
                                </h:outputText>
                            </f:facet>
                        </p:column>

                    </p:dataTable>
                    
                    <p/>
                    
                    <p:commandButton value="OK" style="vertical-align : middle"
                                     action="#{editShoppingCartController.doOK()}"/>

                    <p:spacer width="20"/>
                    
                    <p:selectOneMenu value="#{editShoppingCartController.selectedProduct}" converter="#{productConverter}"
                                     style="vertical-align : middle">
                        <f:selectItems value="#{productList}" var="product" 
                                       itemLabel="#{product.name}"
                                       itemValue="#{product}"/>
                    </p:selectOneMenu>

                    <p:spacer width="10"/>
                    
                    <p:commandButton value="Add to cart" style="vertical-align : middle"
                                     update="itemTable"
                                     actionListener="#{editShoppingCartController.addItemToCart()}"/>

                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/listShoppingCarts.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>
        <ui:composition template="./template.xhtml">
            <ui:define name="content">

                <h1>Shopping Carts</h1>

                <p:messages autoUpdate="true" showDetail="true"/>
                
                <h:form>

                    <p:dataTable value="#{shoppingCarts}" var="cart">

                        <p:column style="text-align: center">
                            <f:facet name="header">Shopping Cart ID</f:facet>
                            <p:commandLink value="#{cart.id}" 
                                           action="#{listShoppingCartsController.doEditShoppingCart(cart)}"
                                           ajax="false"/>
                        </p:column>

                        <p:column style="text-align: center">
                            <f:facet name="header">#Items</f:facet>
                            <h:outputText value="#{cart.numberOfItems}"/>
                        </p:column>

                        <p:column style="text-align: right">
                            <f:facet name="header">Total</f:facet>
                            <h:outputText value="#{cart.total}">
                                <f:convertNumber type="currency" locale="de_DE" />
                            </h:outputText>
                        </p:column>

                    </p:dataTable>

                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="/css/default.css"/>
        <title>Shopping Cart Demo</title>
    </h:head>

    <h:body>
        <div id="container">
            <div id="top">
                <p><b>Warenkorbhandling</b> - <i>Intershop Programmier-Assessment</i></p>
            </div>

            <div id="content">
                <ui:insert name="content">Content</ui:insert>
            </div>

            <div id="bottom">
                <p>Author: Sven Saller, saller.sven@googlemail.com</p>
            </div>
        </div>
    </h:body>

</html>